"""add_zakat_settings_table

Revision ID: 234eb884bb52
Revises: 5cc329b354e8
Create Date: 2026-07-12 15:11:32.096932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234eb884bb52'
down_revision: Union[str, None] = '5cc329b354e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zakat_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('gold_price_per_gram', sa.Float(), nullable=False),
    sa.Column('nisap_amount_lira', sa.Float(), nullable=False),
    sa.Column('is_auto_sync', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_settings_organization_id'), 'zakat_settings', ['organization_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zakat_settings_organization_id'), table_name='zakat_settings')
    op.drop_table('zakat_settings')
    # ### end Alembic commands ###
