"""add_subscription_and_student_tables

Revision ID: 5000c8320301
Revises: 2026_07_12_initial
Create Date: 2026-07-12 14:50:58.727297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5000c8320301'
down_revision: Union[str, None] = '2026_07_12_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=200), nullable=False),
    sa.Column('parent_phone', sa.String(length=20), nullable=False),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_organization_id'), 'students', ['organization_id'], unique=False)
    op.create_index(op.f('ix_students_parent_phone'), 'students', ['parent_phone'], unique=False)
    op.create_table('student_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('check_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('memorized_pages', sa.Integer(), nullable=False),
    sa.Column('current_surah', sa.String(length=100), nullable=False),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_progress_student_id'), 'student_progress', ['student_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('card_token', sa.String(length=100), nullable=True),
    sa.Column('next_charge_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_campaign_id'), 'subscriptions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_donor_id'), 'subscriptions', ['donor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_donor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_campaign_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_student_progress_student_id'), table_name='student_progress')
    op.drop_table('student_progress')
    op.drop_index(op.f('ix_students_parent_phone'), table_name='students')
    op.drop_index(op.f('ix_students_organization_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
