"""add_sponsorships_and_banners_tables

Revision ID: 851af90a4eff
Revises: 234eb884bb52
Create Date: 2026-07-12 15:18:41.460291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851af90a4eff'
down_revision: Union[str, None] = '234eb884bb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('bg_color', sa.String(length=50), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banners_organization_id'), 'banners', ['organization_id'], unique=False)
    op.create_table('student_sponsorships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_sponsorships_donor_id'), 'student_sponsorships', ['donor_id'], unique=False)
    op.create_index(op.f('ix_student_sponsorships_student_id'), 'student_sponsorships', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_sponsorships_student_id'), table_name='student_sponsorships')
    op.drop_index(op.f('ix_student_sponsorships_donor_id'), table_name='student_sponsorships')
    op.drop_table('student_sponsorships')
    op.drop_index(op.f('ix_banners_organization_id'), table_name='banners')
    op.drop_table('banners')
    # ### end Alembic commands ###
